apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: k-s-dev
build:
  artifacts:
    - image: fastapi-sample
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - manifest
