apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-sample
  name: fastapi-sample
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: fastapi-sample
